name: Trigger auto deployment for asdfasdfascasdc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '//**'
    - '.github/workflows/asdfasdfascasdc-AutoDeployTrigger-219bac31-3510-4ac2-9d0d-827414f1d4de.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASDFASDFASCASDC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASDFASDFASCASDC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASDFASDFASCASDC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.ASDFASDFASCASDC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASDFASDFASCASDC_REGISTRY_PASSWORD }}
          containerAppName: asdfasdfascasdc
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/asdfasdfascasdc:${{ github.sha }}
          dockerfilePath: Dockerfile


