name: Trigger auto deployment for fasdfasdfasdfasfd

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/fasdfasdfasdfasfd-AutoDeployTrigger-b84be74d-bf08-478b-8bf2-f07505f2057f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FASDFASDFASDFASFD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FASDFASDFASDFASFD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FASDFASDFASDFASFD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: tmregtest.azurecr.io
          registryUsername: ${{ secrets.FASDFASDFASDFASFD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASDFASDFASDFASFD_REGISTRY_PASSWORD }}
          containerAppName: fasdfasdfasdfasfd
          resourceGroup: tmauldin-test
          imageToBuild: tmregtest.azurecr.io/fasdfasdfasdfasfd:${{ github.sha }}
          


